### ISSUE TITLE
mc_mujoco dependence to HRP4

### ISSUE THREAD

**Issue by ArnaudDmt** [mc-rtc/superbuild-extensions#3]
https://github.com/mc-rtc/superbuild-extensions/blob/01a9192c8e2a3e48cb3427a0ddcc479559057044/interfaces/mc_mujoco.cmake#L32

On this line, we state that hrp4_mj_description depends on hrp4 if WITH_HRP4 is set to true, but this target does not exist (I get the error `get_property could not find TARGET hrp4.  Perhaps it has not yet been created`). I think what you wanted to write is mc-hrp4.

**Comment by gergondet** [comment]
Thanks @ArnaudDmt 

That's because `hrp4` was recently renamed `hrp4_description` by @arntanguy 

Do you mind creating a PR to replace `hrp4` with `hrp4_description` here?
